skeleton_attachment_set("hat", "none");
skeleton_attachment_set("pubic", "char_peasant/pubic");
skeleton_attachment_set("head", "char_peasant/head");
skeleton_attachment_set("hoodie_on", "none");
skeleton_attachment_set("hoodie_under", "none");
skeleton_attachment_set("torso", "char_peasant/torso");
skeleton_attachment_set("arm", "char_peasant/arm");
skeleton_attachment_set("backarm", "char_peasant/backarm");
skeleton_attachment_set("mainhand", "none");
skeleton_attachment_set("leg", "char_peasant/leg");
skeleton_attachment_set("backleg", "char_peasant/backleg");
skeleton_attachment_set("foot", "char_peasant/foot");
skeleton_attachment_set("backfoot", "char_peasant/backfoot");
skeleton_attachment_set("hand", "char_peasant/hand");
skeleton_attachment_set("backhand", "char_peasant/backhand");
skeleton_attachment_set("fist", "char_peasant/fist");
skeleton_attachment_set("backfist", "char_peasant/backfist");
skeleton_attachment_set("shoulder", "none");
skeleton_attachment_set("backshoulder", "none");
skeleton_attachment_set("offhand", "none");
skeleton_attachment_set("backpack", "none");

scr_set_max_health(60);
